<!DOCTYPE html>
<html>
    <body>
        <h1>Cars</h1>
        <div>
            <a class="new-car" href="/cars/new">add new</a>
        </div>

        <br>

        <table border="1" style="border-collapse: collapse;">
            <tr>
                <td>id</td>
                <td>Model</td>
                <td>Pictures</td>
            </tr>

            <?php foreach ($cars as $car) : ?>
                <tr class="tr">
                    <td><?= $car['id'] ?></td>
                    <td><?= $car['model'] ?></td>
                    <td>
                        <?php foreach ($car['pictures'] as $picture) : ?>
                        <img width="100px" src="images/<?= $picture['name'] ?>" />
                        <?php endforeach ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </body>
</html>